### ISSUE TITLE
程序上报后，用手机学工查看发现“所在地点”是一串数字

### ISSUE THREAD

**Issue by yhao-z** [lidongj/yqxx#12]
![$U{ZX4PDI@35A{_AF{II 2G](https://user-images.githubusercontent.com/59129069/129508508-dab1001c-bece-49de-b2c5-077b38aab739.jpg)

数字是230000-230100-230103，应该是黑龙江省哈尔滨市南岗区的意思，但是为什么显示数字呢？

**Comment by billchenchina** [comment]
配置文件更新了，记得看 https://github.com/billchenchina/yqxx#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%A8%A1%E6%9D%BF

**Comment by billchenchina** [comment]
定位信息相关示例
```yaml
# 定位信息建议通过 https://lbs.amap.com/demo/javascript-api/example/geocoder/regeocoding F12 获取
# 定位省
kzl6: '黑龙江省'

# 定位市
kzl7: '哈尔滨市'

# 定位区
kzl8: '南岗区'

# 定位详细地址
# 街道名+门牌号
kzl9: '教化街30号'

# 定位信息
# 地图定位地点
kzl10: '黑龙江省哈尔滨市南岗区花园街道教化街哈尔滨工业大学'

```
